pylint:
  image: python:2.7
  script:
    - pip install pylint pytest pycodestyle --quiet
    - cd lettuce
    - PY_FILES=`find features/{dhcpv4,dhcpv6,other_tests}/ -name '*.py'`
    - PY_FILES="$PY_FILES feat2py.py"
    - echo "$PY_FILES"
    - pylint --rcfile=../pylint.rc $PY_FILES
    - pycodestyle --max-line-length=2000 --function-rgx='[a-z_][a-z0-9_]{2,75}$' --ignore=E722 $PY_FILES
